<!doctype html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>php class demo!</title>
  </head>
  <body>

<form method="POST">
<input name="title">
<button type="submit">Submit</button>
</form>

<?php
$title = $_POST['title'] ?? "";
$h1 = "<h1>Hello</h1>";
$sentence = "This is generated by PHP";
echo $title. $sentence;

?>

<p>Goodbye</p>

  </body>
</html>